# Generated by Django 2.2.5 on 2020-01-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Contact',
        ),
    ]
