# Generated by Django 2.2.5 on 2020-02-02 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20200202_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 9, 6, 3, 676566, tzinfo=utc)),
        ),
    ]
