# Generated by Django 2.2.5 on 2020-02-02 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_searches_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('abstract', models.CharField(max_length=400)),
                ('pdf_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='searches',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 10, 6, 32, 491043, tzinfo=utc)),
        ),
    ]
