# Generated by Django 2.2.5 on 2020-02-02 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20200202_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
