# Generated by Django 2.2.5 on 2020-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='article_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
