# Generated by Django 2.2.5 on 2020-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
