# Generated by Django 2.2.5 on 2020-02-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
    ]
