# Generated by Django 2.2.5 on 2020-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_remove_article_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searches',
        ),
    ]
